name: Deploy production site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Navigate to repo
        run: cd $GITHUB_WORKSPACE
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install deps
        run: npm install
      - name: Build docs
        run: npm run build
      - name: Setup wrangler
        run: echo $WRANGLER_FILE | base64 --decode > wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiKey: ${{ secrets.APIKEY }}
          apiToken: ${{ secrets.APITOKEN }}
          email: ${{ secrets.EMAIL }}
#           environment: ${{ secrets.environment }}
#           workingDirectory: ${{ secrets.workingDirectory }}
#           wranglerVersion: ${{ secrets.wranglerVersion }}
#           secrets: ${{ secrets.secrets }}
